# Secure multi-party computation

La Secure multi-party computation (SMPC) è una sottocategoria della crittografia che si pone come obiettivo quello di  elaborare metodi di calcolo congiunto di una funzione sugli input privati di  due o più parti coinvolte.

A differenza dei compiti crittografici tradizionali, secondo i quali la crittografia  ha come fine ultimo quello di garantire la sicurezza e l’integrità della comunicazione o dell’archiviazione, e l’avversario è esterno al sistema dei partecipanti; la crittografia del modello informatico che andremo di seguito ad analizzare, ha come finalità quella di proteggere la privacy dei partecipanti l’uno dall’altro.

Ci troviamo in un periodo storico in cui i dati, col passare degli anni, stanno diventando un elemento sempre più  centrale per le dinamiche economiche ed informatiche e, in quanto tali, nuovo oggetto di interesse per le aziende. Il massivo incremento della loro importanza in campo economico e informatico trova una spiegazione nel cambiamento/ incremento della loro funzione. Se infatti inizialmente i dati venivano considerati come semplici “informazioni” relative agli utenti, attualmente  essi si sono evoluti e trasformanti in potenziali nuovi metodi di profitto.

Questo processo di cambiamento della funzione e del valore dei dati ha portato alla nascita di un nuovo modello di business primario, attualmente comune a molte delle più grandi aziende, e priorità di tante altre, basato prettamente sulla monetizzazione dei dati relativi agli utenti.

Per fare in modo che l’applicazione di un simile modello di business risulti efficace, è necessario tuttavia effettuare la raccolta di grandi quantità di dati,  ne consegue che il successo di tale operazione sarà  tanto più significativo quante più correlazioni e rapporti di casualità sarà possibile trovare combinando diverse fonti dati. E’ necessario però considerare tutte le problematiche derivanti da questa nuova dinamica.  

Uno dei sottoprodotti potenzialmente rischiosi di questo processo è ad esempio  la possibile violazione della privacy individuale della persona, in quanto le aziende, incrementando la quantità di dati, possiederanno molte informazioni personali dei loro utenti.

Per far fronte a questa possibile problematica sono state studiate e sviluppate molteplici soluzioni  nelle quali sia possibile utilizzare fonti dati diverse, senza però dover necessariamente centralizzare l’informazione. Questa tecnica fa in modo che la privacy individuale degli utenti venga protetta e garantisce  che nessuna informazione venga rivelata a terzi nel corso delle operazioni.

Le nuove dinamiche relative alla sicurezza dei dati stileranno dunque  le basi e le premesse  dell’attuale processo per la sicurezza chiamato Secure multiparty computation (SMPC). In altri termini , grazie al SMPC, sarà possibile consentire ai Data Scientist e Data Analyst di operare sui dati senza il bisogno di esporli o spostarli dalla loro sede di storage di partenza.

\newpage

## Panoramica

In una SMPC prendiamo in considerazione un dato numero di partecipanti, che al fine delle analisi chiameremo $p_1, p_2, ..., p_N$, ad ognuno di essi verranno associati i propri dati privati, che invece chiameremo  $d_1, d_2, ..., d_N$. L’intento del processo nasce dalla necessità dei partecipanti di  calcolare il valore di una funzione pubblica con i loro dati privati: $F(d_1, d_2, ..., d_N)$ mantenendo però i loro input segreti.

Facciamo un esempio: supponiamo di avere tre parti che chiameremo rispettivamente Alice, Bob e Charlie. A ciascuno di loro sono associati  i rispettivi input $x$, $y$ e $z$ che denotano i loro stipendi. Essi hanno come obbiettivo quello di scoprire quale sia tra i tre stipendi che percepiscono quello più alto, senza però rivelare  agli altri quanto guadagna  ciascuno di loro.

Questa premessa  si traduce Matematicamente nel seguente calcolo: $(x,y,z) = max(x, y, z)$

Se ci fosse una parte esterna fidata ( ipotizziamo che i tre partecipanti abbiano un amico comune, lo chiameremo Tony, che deve necessariamente mantenere i segreti delle parti coinvolte ), ognuno dei partecipanti potrebbe  comunicare il proprio stipendio a Tony, così facendo lui potrebbe calcolare quale tra i tre è quello maggiore e, in seguito,  riferire quel numero a tutti loro.

L’obiettivo di SMPC è quello di evitare la situazione in cui i partecipanti, una volta portato a termine il confronto, vengano a conoscenza di un ulteriore dato rispetto al proprio di partenza o  rispetto all’output del processo. Per questo motivo il SMPC si pone come scopo quello di progettare un protocollo nel quale , scambiando messaggi solo tra di loro, Alice, Bob e Charlie possono ancora calcolare $F(x, y, z)$ senza però rivelare  il loro stipendio agli altri e senza dover dipendere da terzi. Essi infatti, durante l’esecuzione di questo protocollo, non dovrebbero venire a conoscenza di più dati di quanti ne saprebbero interagendo con un ipotetico Tony incorruttibile e perfettamente degno di fiducia.

In particolare, tutto ciò  di cui le parti possono venire a conoscenza è ciò che loro stesse possono apprendere dall’output del confronto e dal loro stesso input. Così nell’esempio precedente, se l’output è $z$ allora Charlie impara che il suo  è il valore massimo, mentre Alice e Bob imparano (se $x$, $y$ e $z$ sono distinti), che il loro input non è uguale al massimo, e che il massimo è uguale a $z$. Lo scenario di base può essere facilmente generalizzato ai casi in cui le parti hanno diversi input e output, e la funzione fornisce valori diversi alle diverse parti.

\newpage

Un protocollo di calcolo sicuro multipartitico deve offrire alcune garanzie di sicurezza,  valide anche nei casi in cui alcune delle parti  siano in collusione o  cerchino di violarne le regole. Queste garanzie possono essere definite come qui di seguito:

- **Input Privacy**: Nessuna delle parti corrotte (o suo sottoinsieme) deve in nessun modo essere in grado di derivare alcuna informazione sui dati appartenenti alle altre parti, ad eccezione di quanto rivelato dal risultato finale dell’operazione.
- **Correctness**: Nessuna delle parti corrotte (o suo sottoinsieme) deve essere in grado di indurre una parte onesta a produrre un risultato errato.Un protocollo di calcolo sicuro multipartitico deve offrire alcune garanzie di sicurezza, persino se alcune delle parti fossero in collusione o cercassero di violarne le regole.

## Garanzie di sicurezza

Per fare in modo che Un protocollo di calcolo a più parti sia considerato efficace, esso deve garantire degli standard di sicurezza e, Nella crittografia moderna, la sicurezza di un protocollo è strettamente legata ad una dimostrazione della sicurezza stessa del protocollo. La dimostrazione di sicurezza è da considerarsi una dimostrazione matematica in cui l’affidabilità di un protocollo è ridotta a quella della sicurezza delle sue primitive sottostanti. Tuttavia, non è sempre possibile formalizzare la verifica di sicurezza del protocollo crittografico basata sulla conoscenza delle parti e sulla correttezza del protocollo stesso.

\newpage

Per i protocolli MPC, l’ambiente in cui il protocollo opera è associato alla definizione del paradigma del mondo reale e del mondo ideale. Non è possibile dire che le parti non imparino nulla, poiché devono imparare l’output dell’operazione, e l’output dipende dagli input. Inoltre, la correttezza dell’output non è garantita, poiché la correttezza dell’output dipende dagli input delle parti, e si deve supporre che gli input siano corrotti.
Il paradigma del mondo reale/mondo ideale afferma due mondi che possiamo cosi definire e descrivere: 

- Nel modello del mondo ideale, esiste una parte incorruttibile fidata a cui ogni partecipante al protocollo invia il suo input. Questa parte fidata calcola la funzione da sola e rimanda l’output appropriato ad ogni parte senza rivelare ulteriori dati se non l’output del sistema. 
- Al contrario, nel modello del mondo reale, non esiste una parte fidata e tutto ciò che le parti possono fare è scambiare messaggi tra loro senza ricorrere ad un interlocutore esterno. Un protocollo è detto sicuro se non si può imparare di più sugli input privati di ogni parte nel mondo reale di quanto si potrebbe imparare nel mondo ideale. Nel mondo ideale, nessun messaggio viene scambiato tra le parti, quindi i messaggi scambiati nel mondo reale non possono rivelare alcuna informazione segreta agli altri utenti.

Il paradigma mondo reale/mondo ideale fornisce una semplice astrazione delle complessità di MPC per consentire la costruzione di un'applicazione sotto la premessa che il protocollo MPC nel suo nucleo sia in realtà un'esecuzione ideale. Se l'applicazione è sicura nel caso ideale, allora è sicura anche quando viene eseguito un protocollo reale.

A differenza delle applicazioni crittografiche tradizionali, come la crittografia o la firma, si deve assumere che l’avversario in un protocollo MPC sia uno dei giocatori impegnati nel sistema (o che controlla le parti interne). E che dunque Quella/e parti corrotte possano esse stesse colludere per violare la sicurezza del protocollo dall'interno. 

\newpage

Sia $n$ il numero di parti nel protocollo e $t$ il numero di parti che possono essere avversarie. I protocolli e le soluzioni per il caso di $t< n/2$ (cioè quando si assume una maggioranza onesta) sono diversi da quelli in cui non viene fatta tale assunzione,quelli cioè dove le parti avversarie all’interno del sistema siano presenti in numero maggiore rispetto alle parti oneste. Quest’ultimo scenario include l’importante caso di calcolo a due parti in cui uno dei partecipanti può essere corrotto, e il caso generale in cui un numero illimitato di partecipanti è corrotto e collude per attaccare i partecipanti onesti.

Gli avversari affrontati dai diversi protocolli possono essere classificati in base a quanto, nel loro tentativo di eludere il sistema, sono disposti a deviare dal protocollo. Ci sono essenzialmente due tipi di avversari, ognuno dei quali dà luogo a diverse forme di sicurezza (e ognuno si adatta a diversi scenari del mondo reale):

- **Sicurezza semi-onesta (passiva)**: In questo caso, si assume che le parti corrotte cooperino semplicemente per raccogliere informazioni dal protocollo, ma non si discostino dalle specifiche del protocollo. Questo è un tipo di avversario semplice e ingenuo, che produce una sicurezza debole in situazioni reali. Tuttavia, i protocolli che raggiungono questo livello di sicurezza impediscono la perdita involontaria di informazioni tra le parti (altrimenti collaboranti), e sono quindi utili se questa è l'unica preoccupazione. Inoltre, i protocolli nel modello semi-onesto sono abbastanza efficienti, e sono spesso un primo passo importante per raggiungere livelli più alti di sicurezza.
- **Sicurezza malevola (attiva)**: In questo caso, l’avversario può arbitrariamente discostarsi dall'esecuzione del protocollo nel suo tentativo di ingannare. I protocolli che raggiungono la sicurezza in questo modello forniscono una garanzia di sicurezza molto alta. Il problema sorge Nel caso in cui si presenti una maggioranza delle parti che si comportano scorrettamente. In questo specifico caso , cioè quello di maggioranza disonesta,  L’unica cosa che un avversario può fare  è far sì che le parti oneste interrompano  il processo avendo rilevato l’imbroglio. Ne consegue dunque che Se le parti oneste ottengono l’output, allora hanno la garanzia che esso sia corretto. Anche in questi casi La loro privacy è sempre preservata.

\newpage

La sicurezza contro gli avversari attivi porta tipicamente ad una riduzione dell’efficienza che porta alla sicurezza nascosta, una forma ridotta di sicurezza attiva. La sicurezza nascosta cattura situazioni più realistiche, in cui gli avversari attivi sono disposti a barare ma solo nel caso in cui non vi è la possibilità che il loro tentativo di imbroglio possa venire scoperto poiché, per esempio, tale dinamica potrebbe compromettere o danneggiare la loro reputazione impedendogli così di poter collaborare in futuro con altre parti oneste.

Di conseguenza i protocolli che sono segretamente sicuri forniscono meccanismi per garantire che, se alcune delle parti non seguono le istruzioni, allora sarà notato con alta probabilità. In un certo senso, gli avversari segreti sono quelli considerati attivi ma costretti ad agire passivamente a causa di preoccupazioni esterne non crittografiche (ad esempio la possibilità di compromettere il business). Questo meccanismo stabilisce un ponte tra i due modelli nella speranza di trovare protocolli che siano efficienti e abbastanza sicuri nella pratica.

Come per molti protocolli crittografici, la sicurezza di un protocollo MPC può basarsi su alcuni diversi presupposti:

- **Computazionale** (cioè basata su qualche problema matematico, come la fattorizzazione) o **incondizionata**, cioè basata sull'indisponibilità fisica dei messaggi sui canali (di solito con qualche probabilità di errore che può essere resa arbitrariamente ridotta).
- **Il modello potrebbe assumere diverse dinamiche**: ad esempio che i partecipanti utilizzino una rete sincronizzata dove un messaggio inviato a un “tick” arriva sempre al “tick” successivo, oppure che esista un canale di trasmissione sicuro e affidabile, o ancora che esista un canale di comunicazione sicuro tra ogni coppia di partecipanti dove un avversario non può leggere, modificare o generare messaggi nel canale, ecc.

\newpage

## Two-party computation

Una particolare sotto-categoria delle SMPC che andremo di seguito ad analizzare è la Two-party computation. Questa categoria descrive uno scenario in cui 2 parti parti comunicano tra di loro per la risoluzione di un problema, senza però scambiarsi informazioni sensibili e senza ricorrere all’utilizzo di una terza parte fidata.
Lo scenario a due parti è particolarmente interessante ai fini di un’analisi, in quanto non solo presenta delle diversità dal punto di vista delle applicazioni, ma anche perché a questo scenario a due si possono applicare tecniche speciali che non si applicano nel caso a più parti. Infatti, il calcolo sicuro a più parti è stato presentato per la prima volta nell’impostazione a due parti. Il lavoro originale è spesso citato come proveniente da uno dei due articoli di Yao; anche se gli articoli non contengono effettivamente quello che ora è noto come il Yao’s garbled circuit protocol.

Il protocollo di base di Yao è sicuro contro gli avversari semi-onesti. Possiamo ritenere questo protcollo estremamente efficiente in termini di numero di passaggi in quanto questi sono costanti, e possiamo definirlo indipendente dalla funzione obiettivo che viene valutata. La funzione è vista come un circuito booleano, con ingressi in binario di lunghezza fissa. Un circuito booleano è un insieme di porte collegate con tre diversi tipi di fili: fili di ingresso al circuito, fili di uscita al circuito e fili intermedi. Ogni porta riceve due fili d’ingresso e ha un singolo filo d’uscita che potrebbe essere fan-out (cioè essere passato a più porte al livello successivo). La semplice valutazione del circuito viene fatta valutando ogni porta a turno e assumendo che le porte siano state ordinate topologicamente. Il gate è rappresentato come una tabella di verità tale che per ogni possibile coppia di bit (quelli provenienti dal gate dei fili di ingresso) la tabella assegna un unico bit di uscita; che è il valore del filo di uscita del gate. I risultati della valutazione sono i bit ottenuti nei fili di uscita del circuito.

\newpage

Yao ha spiegato come confondere un circuito (nascondere la sua struttura) in modo che due parti, mittente e ricevitore, possano imparare l’uscita del circuito e nient’altro. Ad un alto livello, il mittente prepara il circuito confuso e lo invia al ricevitore, che ignaro valuta il circuito, imparando le codifiche corrispondenti all’uscita sua e del mittente. Poi si limita a rimandare le codifiche del mittente, permettendo a quest’ultimo di calcolare la sua parte di output. Il mittente invia la mappatura dalle codifiche di uscita dei ricevitori e i bit al ricevitore, permettendo a quest’ultimo di ottenere la propria uscita. 
Nel capitolo successivo andremo ad analizzare più in profondità questo processo, spiegandone dettagliatamente la logica di funzionamento. [@Venturi2012]