# Risultati sperimentali

Una volta concluso il processo di conversione dei circuiti e  terminato tutto il sistema di automazione dei processi, si è proceduto con l’analisi sperimentale dei dati raccolti, in modo tale da valutare se questo nuovo approccio sviluppato potesse essere considerato una alternativa possibile o vincente rispetto alle proposte già presenti in letteratura.

Tutte le operazioni computazionali sono state effettuate utilizzando un DELL-XPS 13 9350, la macchina ha le seguenti specifiche:

- Processore: Intel i5-6200U@2.30GHz con 2 core e 4 thread
- Memoria: 8Gb LPDDR3@1866MHz
- Sistema Operativo: Ubuntu 21.04

\newpage

## MVSIS

Nelle prime fasi di sperimentazione si e’ decido di utilizzare MVSIS come motore di sintesi , sia per i circuiti binari che per quelli multivalore. Questo primo approccio è nato dalla volontà di replicare le operazioni che si svolgono solitamente sulla logica binaria per poi applicarle alla logica multivalore.

Per le operazioni di sintesi si sono utilizzati i seguenti comandi

```
read_blif_mv ./prova/blfmv/amd.mv
sweep
eliminate -l 1
simplify -m nocomp
eliminate -l 1
sweep
eliminate -l 5
simplify
sweep
eliminate -l 1
sweep
fullsimp -m nocomp
write_blif_mv ./prova/blfmv/synth/mvsis/amd.mv
```
Con questi comandi andiamo ad attuare una sintesi del  circuito preso in ingresso, nello specifico vengono effettuate tutte le operazioni  necessarie di pulizia e di rimozione di nodi inutili tramite i comandi _eliminate_ e _sweep_. Successivamente, tramite _simplify_ e _fullsimp_, il circuito viene semplificato su due livelli: sia  per quanto concerne i nodi presenti all’interno del circuito , sia per quanto riguarda il circuito stesso  nella sua interezza.

Questi comandi sono la conversione della variante **MVSIS** di _script.rugged_ usato con il tool per la logica binaria SIS.  In questo caso, però, Non è stato possibile operare una conversione 1:1 dello script in quanto non tutti i comandi sono replicabili.

Per far fronte alla mancanza di replicabilità di alcuni comandi in questo sistema, è stato necessario eseguire un’ulteriore ricerca Sia In rete che in altri paper riguardanti l’argomento. Quello che ne viene dedotto è che è stato creato ed esiste un determinato script, chiamato _mvsis.rugged_ che ,  secondo la nostra ricerca, dovrebbe rappresentare la vera conversione adattata per il multivalore. Purtroppo però non è stato possibile in alcun modo reperire questo file in nessun repository, rendendolo quindi per noi non utilizzabile ai fini delle analisi.

\newpage

### Conversione multivalore fissa

Come primo approccio alla conversione da binaria a multivalore abbiamo optato per lo stesso valore di dominio per tutti i circuiti. La scelta è stata quella di andare ad aggiungere altri 2 valori rispetto a ad un circuito binario utilizzando il modulo 3.

| NOME CIRC | COSTO BOOL | INPUT ALICE | INPUT BOB | DOMINIO MULTI | COSTO MULTI | INPUT ALICE | INPUT BOB | % Guadagno |
|-----------|------------|-------------|-----------|---------------|-------------|-------------|-----------|------------|
| amd       | 469        | 7           | 7         | 3             | 47568       | 3           | 4         | -10042%    |
| tms       | 322        | 4           | 4         | 3             | 2048        | 2           | 2         | -536%      |
| pdc       | 2818       | 7           | 7         | 3             | 1310720     | 4           | 4         | -46412%    |
| mlp4      | 594        | 4           | 4         | 3             | 784         | 2           | 2         | -32%       |
| apla      | 343        | 5           | 5         | 3             | 1029        | 2           | 3         | -200%      |
| f51m      | 261        | 4           | 4         | 3             | 340         | 2           | 2         | -30%       |
| m4        | 974        | 4           | 4         | 3             | 1601        | 2           | 2         | -64%       |
| newtpla2  | 48         | 5           | 5         | 3             | 2048        | 2           | 3         | -4167%     |
| test1     | 1095       | 4           | 4         | 3             | 1280        | 2           | 2         | -17%       |
| m2        | 339        | 4           | 4         | 3             | 1121        | 2           | 2         | -231%      |
| br2       | 179        | 6           | 6         | 3             | 16384       | 3           | 3         | -9053%     |
| alu1      | 83         | 6           | 6         | 3             | 5122        | 3           | 3         | -6071%     |
| sqr6      | 197        | 3           | 3         | 3             | 276         | 1           | 2         | -40%       |
| bench     | 198        | 3           | 3         | 3             | 256         | 1           | 2         | -29%       |
| in5       | 446        | 7           | 7         | 3             | 117440512   | 6           | 6         | -26331853% |
| newtpla1  | 33         | 5           | 5         | 3             | 1024        | 2           | 3         | -3003%     |
| m3        | 571        | 4           | 4         | 3             | 1169        | 2           | 2         | -105%      |
| newapla   | 83         | 6           | 6         | 3             | 9728        | 3           | 3         | -11620%    |
| l8err     | 454        | 4           | 4         | 3             | 337         | 2           | 2         | 26%        |
| t4        | 238        | 6           | 6         | 3             | 10240       | 3           | 3         | -4203%     |
| br1       | 252        | 6           | 6         | 3             | 16384       | 3           | 3         | -6402%     |
| fout      | 442        | 3           | 3         | 3             | 320         | 1           | 2         | 28%        |
| mp2d      | 136        | 7           | 7         | 3             | 7           | 3           | 4         | 95%        |
| alu2      | 225        | 5           | 5         | 3             | 1282        | 2           | 3         | -470%      |
| t3        | 131        | 6           | 6         | 3             | 4           | 3           | 3         | 97%        |
| p3        | 385        | 4           | 4         | 3             | 1408        | 2           | 2         | -266%      |
| m1        | 125        | 3           | 3         | 3             | 225         | 1           | 2         | -80%       |
| bcd_div3  | 54         | 2           | 2         | 3             | 32          | 1           | 1         | 41%        |
| alu3      | 139        | 5           | 5         | 3             | 4           | 2           | 3         | 97%        |
| in7       | 182        | 7           | 7         | 3             | 23085056    | 6           | 7         | -12683997% |

Questa tabella racchiude i risultati ottenuti dalla sintesi dei circuiti multivalore e dei circuiti binari. Possiamo notare che nella maggior parte dei casi il circuito binario mantiene ancora una grande efficienza rispetto a quello multivalore.

### MVSIS e dominio variabile

Nella sperimentazione successiva si è voluto testare un dominio variabile in base al MCD, come descritto nel capitolo precedente. Nella seguente tabella vengono mostrati i costi dei circuiti senza sintesi. Possiamo osservare che nella maggior parte dei casi il dominio multivalore senza sintesi ha un costo minore . Questo risultato può essere considerato una conseguenza diretta del minor numero di input che le parti dovranno inserire all’interno del protocollo durante la computazione. Questi input, essendo in minor quantità, rendono l’intero processo di sintesi più leggero e meno costoso.

| NOME CIRC | COSTO BOOL | INPUT ALICE | INPUT BOB | DOMINIO MULTI | COSTO MULTIVALORE | INPUT ALICE | INPUT BOB | % GUADAGNO |
|-----------|------------|-------------|-----------|---------------|-------------------|-------------|-----------|------------|
| amd       | 393216     | 7           | 7         | 4             | 196608            | 3           | 4         | 50%        |
| tms       | 4096       | 4           | 4         | 16            | 1024              | 1           | 1         | 75%        |
| pdc       | 2621440    | 8           | 8         | 4             | 1310720           | 4           | 4         | 50%        |
| mlp4      | 2048       | 4           | 4         | 16            | 512               | 1           | 1         | 75%        |
| apla      | 12288      | 5           | 5         | 4             | 6144              | 2           | 3         | 50%        |
| f51m      | 2048       | 4           | 4         | 16            | 512               | 1           | 1         | 75%        |
| m4        | 4096       | 4           | 4         | 16            | 1024              | 1           | 1         | 75%        |
| newtpla2  | 4096       | 5           | 5         | 4             | 2048              | 2           | 3         | 50%        |
| test1     | 2560       | 4           | 4         | 4             | 1280              | 2           | 2         | 50%        |
| m2        | 4096       | 4           | 4         | 16            | 1024              | 1           | 1         | 75%        |
| br2       | 32768      | 6           | 6         | 16            | 8192              | 1           | 2         | 75%        |
| alu1      | 32768      | 6           | 6         | 16            | 8192              | 1           | 2         | 75%        |
| sqr6      | 705        | 3           | 3         | 8             | 256               | 1           | 1         | 64%        |
| bench     | 512        | 3           | 3         | 4             | 256               | 1           | 2         | 50%        |
| in5       | 1835008    | 9           | 9         | 4             | 117440512         | 6           | 6         | -6300%     |
| newtpla1  | 2048       | 5           | 5         | 4             | 1024              | 2           | 3         | 50%        |
| m3        | 4096       | 4           | 4         | 16            | 1024              | 1           | 1         | 75%        |
| newapla   | 40960      | 6           | 6         | 4             | 20480             | 3           | 3         | 50%        |
| l8err     | 1283       | 4           | 4         | 16            | 512               | 1           | 1         | 60%        |
| t4        | 32768      | 6           | 6         | 16            | 8192              | 1           | 2         | 75%        |
| br1       | 32768      | 6           | 6         | 16            | 8192              | 1           | 2         | 75%        |
| fout      | 640        | 3           | 3         | 4             | 320               | 1           | 2         | 50%        |
| mp2d      | 229376     | 7           | 7         | 128           | 32768             | 1           | 1         | 86%        |
| alu2      | 8192       | 5           | 5         | 4             | 4096              | 2           | 3         | 50%        |
| t3        | 32768      | 6           | 6         | 16            | 8192              | 1           | 2         | 75%        |
| p3        | 3074       | 4           | 4         | 4             | 1792              | 2           | 2         | 42%        |
| m1        | 768        | 3           | 3         | 8             | 256               | 1           | 1         | 67%        |
| bcd_div3  | 64         | 2           | 2         | 4             | 32                | 1           | 1         | 50%        |
| alu3      | 8192       | 5           | 5         | 4             | 4096              | 2           | 3         | 50%        |
| in7       | 1310720    | 9           | 9         | 4             | 335544320         | 6           | 7         | -25500%    |

\newpage
Una vota applicato la sintesi dei circuiti i risultati sono i seguenti:

| NOME CIRC | COSTO BOOL | INPUT ALICE | INPUT BOB | DOMINIO MULTI | COSTO MULTIVALORE | INPUT ALICE | INPUT BOB | % GUADAGNO |
|-----------|------------|-------------|-----------|---------------|-------------------|-------------|-----------|------------|
| amd       | 469        | 7           | 7         | 4             | 47568             | 3           | 4         | -10042%    |
| tms       | 322        | 4           | 4         | 16            | 1024              | 1           | 1         | -218%      |
| pdc       | 2818       | 7           | 7         | 4             | 1310720           | 4           | 4         | -46412%    |
| mlp4      | 594        | 4           | 4         | 16            | 512               | 1           | 1         | 14%        |
| apla      | 343        | 5           | 5         | 4             | 1029              | 2           | 3         | -200%      |
| f51m      | 261        | 4           | 4         | 16            | 272               | 1           | 1         | -4%        |
| m4        | 974        | 4           | 4         | 16            | 1024              | 1           | 1         | -5%        |
| newtpla2  | 48         | 5           | 5         | 4             | 2048              | 2           | 3         | -4167%     |
| test1     | 1095       | 4           | 4         | 4             | 1280              | 2           | 2         | -17%       |
| m2        | 339        | 4           | 4         | 16            | 1024              | 1           | 1         | -202%      |
| br2       | 179        | 6           | 6         | 16            | 8192              | 1           | 2         | -4477%     |
| alu1      | 83         | 6           | 6         | 16            | 4097              | 1           | 2         | -4836%     |
| sqr6      | 197        | 3           | 3         | 8             | 200               | 1           | 1         | -2%        |
| bench     | 198        | 3           | 3         | 4             | 256               | 1           | 2         | -29%       |
| in5       | 446        | 7           | 7         | 4             | 1,17E+08          | 6           | 6         | -26331853% |
| newtpla1  | 33         | 5           | 5         | 4             | 1024              | 2           | 3         | -3003%     |
| m3        | 571        | 4           | 4         | 16            | 1024              | 1           | 1         | -79%       |
| newapla   | 83         | 6           | 6         | 4             | 9728              | 3           | 3         | -11620%    |
| l8err     | 454        | 4           | 4         | 16            | 512               | 1           | 1         | -13%       |
| t4        | 238        | 6           | 6         | 16            | 8192              | 1           | 2         | -3342%     |
| br1       | 252        | 6           | 6         | 16            | 8192              | 1           | 2         | -3151%     |
| fout      | 442        | 3           | 3         | 4             | 320               | 1           | 2         | 28%        |
| mp2d      | 136        | 7           | 7         | 3             | 7                 | 3           | 4         | 95%        |
| alu2      | 225        | 5           | 5         | 3             | 1282              | 2           | 3         | -470%      |
| t3        | 131        | 6           | 6         | 3             | 4                 | 3           | 3         | 97%        |
| p3        | 385        | 4           | 4         | 3             | 1408              | 2           | 2         | -266%      |
| m1        | 125        | 3           | 3         | 3             | 225               | 1           | 2         | -80%       |
| bcd_div3  | 54         | 2           | 2         | 3             | 32                | 1           | 1         | 41%        |
| alu3      | 139        | 5           | 5         | 3             | 4                 | 2           | 3         | 97%        |
| in7       | 182        | 7           | 7         | 3             | 23085056          | 6           | 7         | -12683997% |

I costi vengono notevolmente abbassati nel caso del booleano mentre in quello multivalore rimangono più elevati. Analizzando Questo fenomeno potremmo trovare una spiegazione nel fatto che la sintesi sui circuiti binari è nettamente più sviluppata e sono stati scoperti metodi di sintesi più efficaci rispetto a quelli studiati per una logica multivalore.

Il tool MVSIS infatti, come affermato in precedenza, non è più stato sviluppato ne mantenuto. All’atto pratico si presenta infatti più lento nella sintesi ed ha una gestione della memoria che porta a dump di memoria durante l’analisi di circuiti di grandi dimensioni.

\newpage

## ABC

Avendo potuto appurare che, inizialmente il costo del circuito multivalore possiede dei costi più bassi per via del minor numero di input, ma che la logica binaria può appoggiarsi a degli strumenti di sintesi più ottimizzati, si è provato ad utilizzare un approccio ibrido tra i due.

Sfruttando quindi come input un circuito multivalore ad ABC, questo tool è in grado di convertire automaticamente il circuito da multivalore a binario,  in modo tale da poter utilizzare i suoi algoritmi di sintesi nettamente più ottimizzati.

```
read_blif_mv ./prova/blfmv/amd.mv
strash
compress2
cl
resyn2
cl
write_blif_mv ./prova/blfmv/synth/abc/amd.mv
```

Rispetto a prima però vi sarà la differenza che l’output post sintesi non sarà più un circuito multivalore, bensì uno binario.

\newpage

## ABC e dominio fisso

Come con *MVSIS* abbiamo inizialmente utilizzato un dominio fisso per svolgere una prima analisi.

| NOME CIRC | COSTO BOOL | INPUT ALICE | INPUT BOB | DOMINIO MULTI | COSTO MULTIVALORE | INPUT ALICE | INPUT BOB | % GUADAGNO |
|-----------|------------|-------------|-----------|---------------|-------------------|-------------|-----------|------------|
| amd       | 469        | 7           | 7         | 2             | 1860              | 7           | 7         | -297%      |
| tms       | 322        | 4           | 4         | 2             | 198               | 4           | 4         | 39%        |
| pdc       | 2818       | 7           | 7         | 2             | 6032              | 7           | 7         | -114%      |
| mlp4      | 594        | 4           | 4         | 2             | 764               | 4           | 4         | -29%       |
| apla      | 343        | 5           | 5         | 2             | 213               | 5           | 5         | 38%        |
| f51m      | 261        | 4           | 4         | 2             | 808               | 4           | 4         | -210%      |
| m4        | 974        | 4           | 4         | 2             | 643               | 4           | 4         | 34%        |
| newtpla2  | 48         | 5           | 5         | 2             | 48                | 5           | 5         | 0%         |
| test1     | 1095       | 4           | 4         | 2             | 354               | 4           | 4         | 68%        |
| m2        | 339        | 4           | 4         | 2             | 320               | 4           | 4         | 6%         |
| br2       | 179        | 6           | 6         | 2             | 110               | 6           | 6         | 39%        |
| alu1      | 83         | 6           | 6         | 2             | 83                | 6           | 6         | 0%         |
| sqr6      | 197        | 3           | 3         | 2             | 263               | 3           | 3         | -34%       |
| bench     | 198        | 3           | 3         | 2             | 47                | 3           | 3         | 76%        |
| in5       | 446        | 7           | 7         | 2             | 1336              | 7           | 7         | -200%      |
| newtpla1  | 33         | 5           | 5         | 2             | 33                | 5           | 5         | 0%         |
| m3        | 571        | 4           | 4         | 2             | 381               | 4           | 4         | 33%        |
| newapla   | 83         | 6           | 6         | 2             | 81                | 6           | 6         | 2%         |
| l8err     | 454        | 4           | 4         | 2             | 434               | 4           | 4         | 4%         |
| t4        | 238        | 6           | 6         | 2             | 197               | 6           | 6         | 17%        |
| br1       | 252        | 6           | 6         | 2             | 153               | 6           | 6         | 39%        |
| fout      | 442        | 3           | 3         | 2             | 214               | 3           | 3         | 52%        |
| mp2d      | 136        | 7           | 7         | 2             | 315               | 5           | 6         | -132%      |
| alu2      | 225        | 5           | 5         | 2             | 554               | 5           | 5         | -146%      |
| t3        | 131        | 6           | 6         | 2             | 160               | 6           | 6         | -22%       |
| p3        | 385        | 4           | 4         | 2             | 139               | 4           | 4         | 64%        |
| m1        | 125        | 3           | 3         | 2             | 116               | 3           | 3         | 7%         |
| bcd_div3  | 54         | 2           | 2         | 2             | 46                | 2           | 2         | 15%        |
| alu3      | 139        | 5           | 5         | 2             | 406               | 5           | 5         | -192%      |
| in7       | 182        | 7           | 7         | 2             | 1676              | 7           | 7         | -821%      |

E’ ora possibile notare come i risultati siano già migliorati e , in molti casi,  la sintesi del circuito multivalore risulti essere migliore di quella binaria, tranne in sporadici casi.

## ABC e dominio variabile

Come ultimo test, come in MVSIS,  abbiamo deciso di applicare anche l’approccio MCD.

| NOME CIRC | COSTO BOOL | INPUT ALICE | INPUT BOB | DOMINIO MULTI | COSTO MULTIVALORE | INPUT ALICE | INPUT BOB | % GUADAGNO |
|-----------|------------|-------------|-----------|---------------|-------------------|-------------|-----------|------------|
| amd       | 469        | 7           | 7         | 2             | 1860              | 7           | 7         | -297%      |
| tms       | 322        | 4           | 4         | 2             | 184               | 4           | 4         | 43%        |
| pdc       | 2818       | 7           | 7         | 2             | 6032              | 7           | 7         | -114%      |
| mlp4      | 594        | 4           | 4         | 2             | 669               | 4           | 4         | -13%       |
| apla      | 343        | 5           | 5         | 2             | 213               | 5           | 5         | 38%        |
| f51m      | 261        | 4           | 4         | 2             | 344               | 4           | 4         | -32%       |
| m4        | 974        | 4           | 4         | 2             | 658               | 4           | 4         | 32%        |
| newtpla2  | 48         | 5           | 5         | 2             | 48                | 5           | 5         | 0%         |
| test1     | 1095       | 4           | 4         | 2             | 354               | 4           | 4         | 68%        |
| m2        | 339        | 4           | 4         | 2             | 350               | 4           | 4         | -3%        |
| br2       | 179        | 6           | 6         | 2             | 130               | 6           | 6         | 27%        |
| alu1      | 83         | 6           | 6         | 2             | 774               | 6           | 6         | -833%      |
| sqr6      | 197        | 3           | 3         | 2             | 234               | 3           | 3         | -19%       |
| bench     | 198        | 3           | 3         | 2             | 47                | 3           | 3         | 76%        |
| in5       | 446        | 7           | 7         | 2             | 1336              | 7           | 7         | -200%      |
| newtpla1  | 33         | 5           | 5         | 2             | 33                | 5           | 5         | 0%         |
| m3        | 571        | 4           | 4         | 2             | 388               | 4           | 4         | 32%        |
| newapla   | 83         | 6           | 6         | 2             | 81                | 6           | 6         | 2%         |
| l8err     | 454        | 4           | 4         | 2             | 338               | 4           | 4         | 26%        |
| t4        | 238        | 6           | 6         | 2             | 248               | 6           | 6         | -4%        |
| br1       | 252        | 6           | 6         | 2             | 136               | 6           | 6         | 46%        |
| fout      | 442        | 3           | 3         | 2             | 214               | 3           | 3         | 52%        |
| mp2d      | 136        | 7           | 7         | 2             | 1677              | 7           | 7         | -1133%     |
| alu2      | 225        | 5           | 5         | 2             | 554               | 5           | 5         | -146%      |
| t3        | 131        | 6           | 6         | 2             | 354               | 6           | 6         | -170%      |
| p3        | 385        | 4           | 4         | 2             | 139               | 4           | 4         | 64%        |
| m1        | 125        | 3           | 3         | 2             | 112               | 3           | 3         | 10%        |
| bcd_div3  | 54         | 2           | 2         | 2             | 46                | 2           | 2         | 15%        |
| alu3      | 139        | 5           | 5         | 2             | 406               | 5           | 5         | -192%      |
| in7       | 182        | 7           | 7         | 2             | 1676              | 7           | 7         | -821%      |

In questo caso possiamo appurare che tra i due approcci non ci sono differenze sostanziali, questo  risultato potrebbe essere derivato dalle modalità con cui  abc legge i circuiti multivalore in input.

\newpage

## Conclusioni sui risultati

Una volta terminate tutte le analisi e le sperimentazioni eseguite sui circuiti binari e multivalore siamo stati in grado di trarre alcune informazioni molto importanti riguardanti essi e i loro funzionamenti. Tutti i dati ottenuti da questa sperimentazione ci hanno portati a notare come l'utilizzo della logica multivalore all'interno dei circuiti potrebbe rivelarsi molto interessante in termini di riduzione dei costi relativi ai valori di input che sono richiesti dai circuiti.

La limitazione principale che abbiamo potuto riscontrare è insita nella carenza di strumenti di sintesi a disposizione che possano essere considerati applicabili alla logica multivalore. Come anticipato, solamente **MVSIS** è in grado di gestire e interpretare questo tipo di logica, ma rimane un programma ora mai datato e non più mantenuto, di conseguenza non vi sono al suo interno tool sufficientemente aggiornati o meglio implementati. I nuovi strumenti messi a disposizione, come ad esempio **ABC** accettano in ingresso circuiti multivalore, ma, per poter fare questo, nel loro motore di sintesi essi vengono convertiti in circuiti booleani. L'efficienza e l'efficacia delle nuove funzioni di sintesi attuate da **ABC** hanno reso l'utilizzo di questo software la prima scelta da utilizzare nel caso di circuiti multivalore e binari. 

Applicando un approccio ibrido siamo stati in grado di prendere il meglio dei sintetizzatori presentati. Sfruttando  la riduzione degli input durante la conversione in un dominio maggiore di quello binario combinata all'alta efficacia degli strumenti di sintesi messi a disposizione di **ABC** abbiamo ottenuto i risultati migliori.

\newpage

 **Circuito** | **BINARIO** | **MULTIVALORE** | **MVSIS dom var** | **ABC dom var** | **Riduzione costo. %** 
:------------:|:-----------:|:---------------:|:-----------------:|:---------------:|:----------------------:
 amd          | 393216      | 196608          | 47568             | 1860            | 96,09%                 
 tms          | 4096        | 1024            | 1024              | 184             | 82,03%                 
 pdc          | 2621440     | 1310720         | 1310720           | 6032            | 99,54%                 
 mlp4         | 2048        | 512             | 512               | 669             | -30,66%                
 apla         | 12288       | 6144            | 1029              | 213             | 79,30%                 
 f51m         | 2048        | 512             | 272               | 344             | -26,47%                
 m4           | 4096        | 1024            | 1024              | 658             | 35,74%                 
 newtpla2     | 4096        | 2048            | 2048              | 48              | 97,66%                 
 test1        | 2560        | 1280            | 1280              | 354             | 72,34%                 
 m2           | 4096        | 1024            | 1024              | 350             | 65,82%                 
 br2          | 32768       | 8192            | 8192              | 130             | 98,41%                 
 alu1         | 32768       | 8192            | 4097              | 774             | 81,11%                 
 sqr6         | 705         | 256             | 200               | 234             | -17,00%                
 bench        | 512         | 256             | 256               | 47              | 81,64%                 
 in5          | 1835008     | 117440512       | 117440512         | 1336            | 100,00%                
 newtpla1     | 2048        | 1024            | 1024              | 33              | 96,78%                 
 m3           | 4096        | 1024            | 1024              | 388             | 62,11%                 
 newapla      | 40960       | 20480           | 9728              | 81              | 99,17%                 
 l8err        | 1283        | 512             | 512               | 338             | 33,98%                 
 t4           | 32768       | 8192            | 8192              | 248             | 96,97%                 
 br1          | 32768       | 8192            | 8192              | 136             | 98,34%                 
 fout         | 640         | 320             | 320               | 214             | 33,13%                 

\newpage

Questa tabella rappresenta la differenza di costo percentuale tra i due metodi più efficaci provati per ogni motore di sintesi. 

Come possiamo notare come questo tipo di metodica, definita ibrida, risulta essere il migliore approccio testato durante questa sperimentazione in quanto i risultati mostrano una riduzione dei costi computazionali in tutti i casi ad eccezione di due e i restanti risultati hanno una percentuale di guadagno sempre superiore al 30% e, nei casi di circuiti con grande quantità di nodi, anche superiore al 100% riducendo notevolmente il costo computazionale.

La tecnica di analisi ibrida offre i risultati migliori in quanto:

- La conversione di dominio ibrida al minimo dimezza i valori di input da inserire dalle parti e l'algoritmo fa in modo che non venga selezione un dominio eccessivamente grande limitando le possibilità a casi utili in contesti reali;
- **ABC** è un tool recente e sempre più ottimizzato, in continuo aggiornamento e dispone di preset ottimizzati per la sintetizzazione dei circuiti.

La tabella riassume anche qual è stata l'evoluzione di questa analisi sperimentale: inizialmente ci si è concentrati su un metodo ottimale di conversione binaria e abbiamo analizzato se effettivamente questa sperimentazione potesse avere dei reali benefici, successivamente si è passati alla sintesi dei circuiti per capire se la sintesi di domini non binari potesse essere efficace come quella binaria. Una volta individuati i tool migliori si è cercato di capire quali tecniche di sintesi potessero essere le migliori fino ad arrivare ai risultati finali con la constatazione che l'approccio ibrido, ad oggi, risulti la tecnica migliore da noi testata.