# Conclusioni

Una volta terminate tutte le analisi e le sperimentazioni eseguite sui circuiti binari e multivalore siamo stati in grado di trarre alcune informazioni molto importanti riguardanti essi e i loro funzionamenti. Tutti i dati ottenuti da questa sperimentazione ci hanno portati a notare come l'utilizzo della logica multivalore all'interno dei circuiti potrebbe rivelarsi molto interessante in termini di riduzione dei costi relativi ai valori di input che sono richiesti dai circuiti.

La limitazione principale che abbiamo potuto riscontrare è insita nella carenza di strumenti di sintesi a disposizione che possano essere considerati applicabili alla logica multivalore. Come anticipato, solamente **MVSIS** è in grado di gestire e interpretare questo tipo di logica, ma rimane un programma ora mai datato e non più mantenuto, di conseguenza non vi sono al suo interno tool sufficientemente aggiornati o meglio implementati. I nuovi strumenti messi a disposizione, come ad esempio **ABC** accettano in ingresso circuiti multivalore, ma, per poter fare questo, nel loro motore di sintesi essi vengono convertiti in circuiti booleani. L'efficienza e l'efficacia delle nuove funzioni di sintesi attuate da **ABC** hanno reso l'utilizzo di questo software la prima scelta da utilizzare nel caso di circuiti multivalore e binari. 

Applicando un approccio ibrido siamo stati in grado di prendere il meglio dei sintetizzatori presentati. Sfruttando  la riduzione degli input durante la conversione in un dominio maggiore di quello binario combinata all'alta efficacia degli strumenti di sintesi messi a disposizione di **ABC** abbiamo ottenuto i risultati migliori.

\newpage

| **Circuito** 	| **BINARIO** | **MULTIVALORE** | **MVSIS dom var** | **ABC dom var** | **Riduzione costo. %** |
|--------------	|-------------|-----------------|-------------------|-----------------|------------------------|
| amd          	| 393216      | 196608          | 47568             | 1860            | 96,09%                 |
| tms          	| 4096        | 1024            | 1024              | 184             | 82,03%                 |
| pdc          	| 2621440     | 1310720         | 1310720           | 6032            | 99,54%                 |
| mlp4         	| 2048        | 512             | 512               | 669             | -30,66%                |
| apla         	| 12288       | 6144            | 1029              | 213             | 79,30%                 |
| f51m         	| 2048        | 512             | 272               | 344             | -26,47%                |
| m4           	| 4096        | 1024            | 1024              | 658             | 35,74%                 |
| newtpla2     	| 4096        | 2048            | 2048              | 48              | 97,66%                 |
| test1        	| 2560        | 1280            | 1280              | 354             | 72,34%                 |
| m2           	| 4096        | 1024            | 1024              | 350             | 65,82%                 |
| br2          	| 32768       | 8192            | 8192              | 130             | 98,41%                 |
| alu1         	| 32768       | 8192            | 4097              | 774             | 81,11%                 |
| sqr6         	| 705         | 256             | 200               | 234             | -17,00%                |
| bench        	| 512         | 256             | 256               | 47              | 81,64%                 |
| in5          	| 1835008     | 117440512       | 117440512         | 1336            | 100,00%                |
| newtpla1     	| 2048        | 1024            | 1024              | 33              | 96,78%                 |
| m3           	| 4096        | 1024            | 1024              | 388             | 62,11%                 |
| newapla      	| 40960       | 20480           | 9728              | 81              | 99,17%                 |
| l8err        	| 1283        | 512             | 512               | 338             | 33,98%                 |
| t4           	| 32768       | 8192            | 8192              | 248             | 96,97%                 |
| br1          	| 32768       | 8192            | 8192              | 136             | 98,34%                 |
| fout         	| 640         | 320             | 320               | 214             | 33,13%                 |
| **MEDIA**     | 230286,73   | 5409911,27      | 5402215,91        | 666,86          | 65,27%                 |


\newpage

Questa tabella rappresenta la differenza di costo percentuale tra i due metodi più efficaci provati per ogni motore di sintesi. 

Come possiamo notare come questo tipo di metodica, definita ibrida, risulta essere il migliore approccio testato durante questa sperimentazione in quanto i risultati mostrano una riduzione dei costi computazionali in tutti i casi ad eccezione di due e i restanti risultati hanno una percentuale di guadagno sempre superiore al 30% e, nei casi di circuiti con grande quantità di nodi, anche superiore al 100% riducendo notevolmente il costo computazionale.

La tecnica di analisi ibrida offre i risultati migliori in quanto:

- La conversione di dominio ibrida al minimo dimezza i valori di input da inserire dalle parti e l'algoritmo fa in modo che non venga selezione un dominio eccessivamente grande limitando le possibilità a casi utili in contesti reali;
- **ABC** è un tool recente e sempre più ottimizzato, in continuo aggiornamento e dispone di preset ottimizzati per la sintetizzazione dei circuiti.

La tabella riassume anche qual è stata l'evoluzione di questa analisi sperimentale: inizialmente ci si è concentrati su un metodo ottimale di conversione binaria e abbiamo analizzato se effettivamente questa sperimentazione potesse avere dei reali benefici, successivamente si è passati alla sintesi dei circuiti per capire se la sintesi di domini non binari potesse essere efficace come quella binaria. Una volta individuati i tool migliori si è cercato di capire quali tecniche di sintesi potessero essere le migliori fino ad arrivare ai risultati finali con la constatazione che l'approccio ibrido, ad oggi, risulti la tecnica migliore da noi testata.

Lo studio dell'utilizzo della logica multivalore ha portato ha dei risultati interessanti nonostante la limitazione data dalla scarsità e obsolescenza degli strumenti di sintesi. Le tecniche analizzate in un'ottica futura potranno affiancare le classiche metodologie binarie in quanto, analizzando i risultati, alcuni tipi di circuiti non giovano della conversione in multivalore generando costi maggiori rispetto alla controparte booleana.

\newpage